import './javascript/loader';
import './javascript/stars-rating';
import './javascript/header';
import './javascript/hero';
import './javascript/weekly-trends-main';
// import './JS/library/library';
//import './javascript/upcoming/upcoming';
import './upcoming/upcoming';
import './javascript/modal-trailer';
import './javascript/global-listener';
import './javascript/scroll-up';
