import './javascript/loader';
import './javascript/stars-rating';
import './javascript/header';
import './javascript/hero';
import './javascript/weekly-trends-main';
import './upcoming/upcoming';
import './javascript/modal-trailer';
import './javascript/global-listener';
import './javascript/scroll-up';
console.log('object');
