import { getGenres } from './javascript/weekly-trends/weekly-trends-genres';
// console.log('object');
getGenres();
import './javascript/loader';
import './javascript/stars-rating';
import './javascript/header/header';
import './javascript/hero/hero';
import './javascript/weekly-trends/weekly-trends-main';
import './javascript/upcoming/upcoming';
import './javascript/modal/modal-trailer';
import './javascript/global-listener';
import './javascript/scroll-up';
